texts = [
	["Food","อาหาร","What"], 
	["Drink","เครื่องดื่ม","What"],
	["Cloth","เสื้อผ้า","What"],
	["Buildings","สิ่งก่อสร้าง","What"],
	["Reading","สินค้าสำหรับอ่าน","What"],
	["Musics & Songs","ดนตรี และ เพลง","What"],
	["Smell","เกี่ยวกับกลิ่น","What"],
	["Pressing","สิ่งที่กดได้","What"],
	["Show","เอาไว้โชว์","What"],
	["Runing","วิ่ง","What"],
	["Laugh","หัวเราะ","What"],
	["Cry","ร้องไห้","What"],
	["Appreciate","ชื่นชม","What"],
	["Emulate","เลียนแบบ","What"],
	["Walk","เดิน","What"],
	["Want to Do","อยากทำ","What"],
	["Increase","เพิ่มขึั้น ยืดขึ้น","What"],
	["Wear","สวมใส่","What"],
	["Look","ดู","What"],
	["Read","อ่าน","What"],
	
	["Dad","พ่อ","Who"],
	["Mum","แม่","Who"],
	["Teacher","ครู","Who"],
	["Child","ลูก","Who"],
	["Darling","แฟน","Who"],
	["Notable People","คนที่น่าชื่นชม","Who"],
	["Enviable People","คนที่น่าอิจฉา","Who"],
	["Supporter","คนที่ช่วยเหลือเรา","Who"],
	["Thai","คนไทย","Who"],
	["American","คนอเมริกา","Who"],
	["Chinese","คนจีน","Who"],
	["Japanese","คนญี่ปุ่น","Who"],
	["Teenager","วันรุ่น","Who"],
	["Men","ผู้ชาย","Who"],
	["Women","ผู้หญิง","Who"],
	["Businessmen","นักธุรกิจ","Who"],
	["Employee","พนักงาน","Who"],
	["Students","นักเรียน","Who"],
	
	
	["World","โลก","Where"],
	["Thailand","ประเทศไทย","Where"],
	["Japan","ญี่ปุ่น","Where"],
	["Bangkok","กรุงเทพ","Where"],
	["The Country","ชนบท","Where"],
	["School","โรงเรียน","Where"],
	["Hospital","โรงพยาบาล","Where"],
	["Shop","ร้านค้า","Where"],
	["Department Store","ห้างสรรพสินค้า","Where"],
	["Beach","ชายหาด","Where"],
	["Gas Station","ปั๊มน้ำมัน","Where"],
	

	["Before","ก่อน","When"],	
	["After","หลัง","When"],	
	["Season Change","เปลี่ยนฤดู","When"],	
	["Summer","ฤดูร้อน","When"],	
	["Winter","ฤดูหนาว","When"],	
	["Rainy","ฤดูฝน","When"],	
	["New Year","เทศกาลปีใหม่","When"],	
	["X-Mas","คริสมาสต์","When"],	
	["Morning","เช้า","When"],	
	["Afternoon","บ่าย","When"],	
	["Noon","เที่ยง","When"],	
	["Evening","เย็น","When"],	
	["Night","กลางคืน","When"],	
	
	
	["Hot-Cold","ร้อน-เย็น","How"],
	["Big-Small","เล็ก-ใหญ่","How"],
	["Ordering","ลำดับก่อนหลัง","How"],
	["Long-Short","ยาว-สั้น","How"],
	["Black-White","ขาว-ดำ","How"],
	["Steps","ขั้นตอน","How"],
	["Tradition","ธรรมเนียมปฏิบัติ","How"],
	["Modern","ทันสมัย","How"]

];
